---
title: "Curriculum Vitae"
---

**Kevin Rue-Albrecht, Computational Biologist (Dipl. Ing., Ph.D.)**

::: {.cv-section}
## {{< fa graduation-cap >}} Education

::: {.cv-entry}
::: {.cv-dates}
2011 - 2015
:::
::: {.cv-title}
PhD - Computational Infection Biology
:::
::: {.cv-location}
University College Dublin (Ireland)
:::
::: {.cv-description}

- Three rotation projects in computational and molecular biology.
- A thesis in computational infection biology.

For more details, please see the [Research Experience](#fa-microscope-research-experience) section below.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2008 - 2011
:::
::: {.cv-title}
Ingénieur diplômé
:::
::: {.cv-location}
École Polytechnique Universitaire Polytech Nice-Sophia (France)
:::
::: {.cv-description}
**Major:** Bioinformatics and Modelling for Biology
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2006 - 2008
:::
::: {.cv-title}
Class Préparatoire aux Grandes Écoles BCPST-Véto
:::
::: {.cv-location}
Lycée Jean Rostand, Strasbourg (France)
:::
::: {.cv-description}
**BCPST:** Biology, Chemistry, Physics, Earth Sciences
:::
:::
:::

::: {.cv-section}
## {{< fa award >}} Fellowships & Awards

::: {.cv-entry}
::: {.cv-dates}
2026 - 2027
:::
::: {.cv-title}
Software Sustainability Institute Research Software Fellowship
:::
::: {.cv-location}
Software Sustainability Institute
:::
::: {.cv-description}
The [Fellowship Programme](https://www.software.ac.uk/programmes/fellowship-programme) supports ambassador for good practice in research software.

For more details, please refer to the [Blog post](https://www.software.ac.uk/news/introducing-2026-fellowship-cohort-insights-and-celebrations) and my [SSI profile](https://www.software.ac.uk/fellowship-programme/kevin-rue-albrecht).
:::
:::

:::

::: {.cv-section}
## {{< fa microscope >}} Research Experience

::: {.cv-entry}
::: {.cv-dates}
2020 - present
:::
::: {.cv-title}
Computational Biologist & Biomedical Data Science Trainer
:::
::: {.cv-location}
[Sims Group](https://www.imm.ox.ac.uk/research/research-groups/sims-group-computational-genomics) (University of Oxford)
:::
::: {.cv-description}
Contributing to computational biology research and training programs in functional genomics and single-cell sequencing analysis.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2017 - 2020
:::
::: {.cv-title}
Postdoctoral Researcher - Computational Biology
:::
::: {.cv-location}
[Sansom Group](https://www.kennedy.ox.ac.uk/research/research-groups/computational-genomics) (University of Oxford)
:::
::: {.cv-description}
Contributed to the study of Inflammatory bowel disease pathogenesis and T-cell development through the development of computational pipelines for bespoke data analysis.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2016 - 2017
:::
::: {.cv-title}
Postdoctoral Researcher - Computational Biology
:::
::: {.cv-location}
[Ratcliffe Group](https://www.ludwig.ox.ac.uk/research/prof-sir-peter-ratcliffe-oxygen-sensing) (University of Oxford)
:::
::: {.cv-description}
Managed data and computational workflows for high-throughput sequencing projects including targeted DNA resequencing, ChIP-seq, and RNA-seq for renal cancer research.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2015 - 2016
:::
::: {.cv-title}
Research associate - Bioinformatics & Biostatistics
:::
::: {.cv-location}
[Wilkins Group](https://profiles.imperial.ac.uk/m.wilkins) (Imperial College London)
:::
::: {.cv-description}
Integrated genetic variation, proteomic and metabolomics data with associated deep phenotype data, in collaboration with the [Morrell Group](https://www.cardiovascular.cam.ac.uk/directory/nmorrell).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2012 - 2015
:::
::: {.cv-title}
PhD - Computational Infection Biology
:::
::: {.cv-location}
University College Dublin (Ireland)
:::
::: {.cv-description}
**Thesis:** Comparative systems biology analyses of the bovine transcriptional response to species of the *Mycobacterium genus*.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2012 -\
Jul 2012
:::
::: {.cv-title}
PhD Rotation Project (3 of 3) - Molecular biology
:::
::: {.cv-location}
[O'Gara Group](https://orcid.org/0000-0003-3866-7161) (University College Dublin)
:::
::: {.cv-description}
Evaluated the role of a gene candidate underlying *Staphylococcus aureus* antibiotic resistance by Sanger sequencing and biofilm assay.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2012 -\
Apr 2012
:::
::: {.cv-title}
PhD Rotation Project (2 of 3) - Molecular biology
:::
::: {.cv-location}
[Ferguson Group](https://www.researchgate.net/scientific-contributions/Neil-Ferguson-38863526) (University College Dublin)
:::
::: {.cv-description}
Expressed and purified a Hepatitis B protein construct for experimental screening of interacting drug fragments.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2011 -\
Jan 2012
:::
::: {.cv-title}
PhD Rotation Project (1 of 3) - Computational biology
:::
::: {.cv-location}
[Shield Group](https://people.ucd.ie/denis.shields/) / [Gordon Group](https://people.ucd.ie/stephen.gordon/) (University College Dublin)
:::
::: {.cv-description}
Predicted *Mycobacterium bovis* epitopes in cattle using *in silico* structure-based modelling.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2010 -\
Sep 2010
:::
::: {.cv-title}
Intern - Computational Biology
:::
::: {.cv-location}

[Shield Group](https://people.ucd.ie/denis.shields/) (University College Dublin)
:::
::: {.cv-description}
Analysed structural disorder in *Saccharomyces cerevisiae* interacting proteins.

Project supervisor: [Dr. Nora Khaldi](https://www.nuritas.com/team/dr-nora-khaldi/)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jul 2009 -\
Aug 2009
:::
::: {.cv-title}
Intern - Molecular Biology
:::
::: {.cv-location}
[INSERM, Unité Mixte de Recherche S725, Biologie des Cellules Dendritiques Humaines](https://academic.oup.com/jimmunol/article-abstract/188/8/3903/7981527) (Strasbourg, France)
:::
::: {.cv-description}
Expressed recombinant MHC class II molecules in HeLa cells.

Project supervisor: [Henri de la Salle](https://orcid.org/0000-0001-5136-0776)
:::
:::
:::

::: {.cv-section}
## {{< fa briefcase >}} Professional Experience

::: {.cv-entry}
::: {.cv-dates}
Oct 2022 -\
Oct 2023
:::
::: {.cv-title}
Software Developer - Consultant
:::
::: {.cv-location}
Self-employed (Oxford, UK)
:::
::: {.cv-description}
Developed three extension packages in the iSEE framework for the analysis and visualisation of omics data sponsored by [Denali Therapeutics Inc](https://www.denalitherapeutics.com/).

- [iSEEindex](https://github.com/iSEE/iSEEindex)
- [iSEEde](https://github.com/iSEE/iSEEde)
- [iSEEpathways](https://github.com/iSEE/iSEEpathways)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2011 -\
Jul 2011
:::
::: {.cv-title}
Software Developer - Intern
:::
::: {.cv-location}
[MEDIT S.A.](https://www.linkedin.com/company/medit-sa/) (Palaiseau, France)
:::
::: {.cv-description}
Implemented functionality for structurally-constrained multiple alignment of protein sequences for the commercial software MED-SuMo.
:::
:::
:::

::: {.cv-section}
## {{< fa chalkboard-user >}} Teaching Experience

::: {.info-banner}
{{< fa circle-info >}} Please note that the following section is a summary; for more details, please visit the [Teaching](teaching.qmd) page.
:::

::: {.cv-entry}
::: {.cv-dates}
2021 - present
:::
::: {.cv-title}
Bioconductor Education Committee
:::
::: {.cv-location}
[Bioconductor](https://bioconductor.org/)
:::
::: {.cv-description}
Co-lead and contributor to the [Bioconductor Education Committee](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#education), developing educational materials and organising training events for the Bioconductor community.

- Delivered lesson [Orchestrating Large-Scale Single-Cell Analysis with Bioconductor](https://carpentries-incubator.github.io/bioc-scrnaseq/) (15-16 September 2025 -- Barcelona, Spain).
- Developed lesson [The Bioconductor project](https://carpentries-incubator.github.io/bioc-project/).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2020 - present
:::
::: {.cv-title}
MSc in Precision Cancer Medicine
:::
::: {.cv-location}
[Department of Oncology](https://www.oncology.ox.ac.uk/) (University of Oxford)
:::
::: {.cv-description}
Lecturer & Internal Assessor for the [MSc in Precision Cancer Medicine](https://www.ox.ac.uk/admissions/graduate/courses/msc-precision-cancer-medicine) program.

Part-time distance-learning course, including lectures and live online tutorials.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2020 - present
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Sims Group](https://www.imm.ox.ac.uk/research/research-groups/sims-group-computational-genomics) (University of Oxford)
:::
::: {.cv-description}
Hands-on training delivered to small groups of researchers for the [Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] covering:

- Genomics on the Linux command line
- Python programming and data science
- R for data science and genomics
- Introduction to single-cell RNAseq data analysis using R
- Spatial Transcriptomics data analysis using R
- Containers for Reproducible Research
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2020
:::
::: {.cv-title}
iSEE: Interactive visualization of SummarizedExperiment objects
:::
::: {.cv-location}
[SIB Days 2020](https://sibdays.sib.swiss/archives/2020/) (Online)
:::
::: {.cv-description}
Co-organised and delivered a 2h30 online workshop (8 June 2020).

- [Workshop materials](https://github.com/iSEE/iSEEWorkshop2020)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2019-\
2020
:::
::: {.cv-title}
R Code Clinic
:::
::: {.cv-location}
Big Data Institute (University of Oxford)
:::
::: {.cv-description}
Volunteer assisting individuals with any R programming questions as part of the [BDI R Code Clinic](https://www.bdi.ox.ac.uk/upcoming-events/bdi-r-code-clinic-programming-with-the-tidyverse) series.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2019
:::
::: {.cv-title}
Interactive visualisation of SummarizedExperiment objects using iSEE
:::
::: {.cv-location}
[Bioconductor conference 2019](http://bioc2019.bioconductor.org/) (New York, USA)
:::
::: {.cv-description}
Co-instructed a 2-hour workshop (26 June 2019).

- [Workshop materials](https://github.com/iSEE/iSEEWorkshop2019)
- [Slides](https://kevinrue.github.io/academic-2023/slides/bioc2019-workshop/)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
Molecular Genetics and Biotech
:::
::: {.cv-location}
University College Dublin (Ireland)
:::
::: {.cv-description}
Teaching assistant of [BMOL20090](https://hub.ucd.ie/usis/!W_HU_MENU.P_PUBLISH?p_tag=MODULE&MODULE=BMOL20090) practicals for undergraduate students.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
Agricultural Microbiology
:::
::: {.cv-location}
University College Dublin (Ireland)
:::
::: {.cv-description}
Teaching assistant of [MICR20010](https://hub.ucd.ie/usis/!W_HU_MENU.P_PUBLISH?p_tag=MODULE&MODULE=MICR20010) practicals for undergraduate students.
:::
:::

:::

::: {.cv-section}
## {{< fa microphone-lines >}} Talks

::: {.cv-entry}
::: {.cv-dates}
2025
:::
::: {.cv-title}
European Bioconductor Conference
:::
::: {.cv-location}
Barcelona, Spain
:::
::: {.cv-description}
**Flash talk:** [Making the Bioconductor EuroBioC2025 hexwall](https://doi.org/10.5281/zenodo.17177748)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2021
:::
::: {.cv-title}
Bioconductor Conference
:::
::: {.cv-location}
Airmeet (Online)
:::
::: {.cv-description}
Oral presentations:

- [Introduction to workshops - Informal welcome](https://www.youtube.com/watch?v=6skphXuBbd4&list=PLdl4u5ZRDMQRA_Fvfg9Bour_x56irZiA2&index=1&t=4s&ab_channel=Bioconductor): Opening talk for the conference
- [velociraptor](https://kevinrue.github.io/velociraptor_talk_bioc2021/): A Bioconductor toolkit for single-cell RNA velocity
- [Bioconductor 20th anniversary](https://kevinrue.github.io/Bioconductor20YearsSlides/): Set up an automated repository converting community contributions into an HTML slide deck
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2019
:::
::: {.cv-title}
Bioconductor Conference
:::
::: {.cv-location}
New York, USA
:::
::: {.cv-description}
Oral presentations:

- [Talk](https://kevinrue.github.io/academic-2023/slides/bioc2019-flashtalk/#/): Interactive and reproducible visualization of `SummarizedExperiment` objects
- [Workshop](https://github.com/iSEE/iSEEWorkshop2019): Interactive visualization of `SummarizedExperiment` objects with `iSEE`
- [Special Interest Group](https://github.com/Bioconductor/BioC2019/issues/25): Extending gene set and signature representations
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2018
:::
::: {.cv-title}
Genome Informatics
:::
::: {.cv-location}
Cambridge, UK
:::
::: {.cv-description}
**Poster:** Promiscuous expression of lincRNAs in medullary thymic epithelial cells
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2017
:::
::: {.cv-title}
NGS-SIG - Single-cell RNA-seq
:::
::: {.cv-location}
Oxford, UK
:::
::: {.cv-description}
**Oral presentation:** Variability of human dendritic cells responses to differentially invasive *Salmonella* strains at single-cell level
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2017
:::
::: {.cv-title}
Bioconductor Conference
:::
::: {.cv-location}
Boston, USA
:::
::: {.cv-description}
Oral presentations:

- `GOexpress`: Visualise and summarise gene expression data using Gene Ontology
- `TVTB`: The VCF Tool Box: an effort to summarise and visualise variants
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2015
:::
::: {.cv-title}
Quantitative Genomics
:::
::: {.cv-location}
London, UK
:::
::: {.cv-description}
**Poster:** `GOexpress`: A R/Bioconductor package for the identification and visualisation of robust gene ontology signatures through supervised learning of gene expression data
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2015
:::
::: {.cv-title}
BOSC - ISMB/ECCB Conference
:::
::: {.cv-location}
Dublin, Ireland
:::
::: {.cv-description}
Oral presentation and poster:

- [Talk](https://f1000research.com/slides/4-248): `GOexpress`: A R/Bioconductor package for the identification and visualisation of robust gene ontology signatures through supervised learning of gene expression data
- [Poster](https://f1000research.com/posters/4-247): `GOexpress`: Identify and visualise gene expression using supervised learning and Gene Ontology
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
Society for General Microbiology (SGM)
:::
::: {.cv-location}
Dublin, Ireland
:::
::: {.cv-description}
**Poster:** Microarray analysis of the bovine macrophage response to *Mycobacterium bovis*, *M. bovis* Bacille Calmette-Guérin (BCG) and *M. avium* subspecies *paratuberculosis*
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
Virtual Institute of Bioinformatics & Evolution (VIBE)
:::
::: {.cv-location}
Carlow, Ireland
:::
::: {.cv-description}
**Oral presentation:** The quest for meaningful visualisation of genome-wide expression data
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
EMBO Conference: Microbiology after the genomics revolution - Genomes 2014
:::
::: {.cv-location}
Paris, France
:::
::: {.cv-description}
**Poster:** Transcriptome analysis reveals differential innate immune response to members of the *Mycobacterium tuberculosis* complex
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
The Acid Fast Club, Summer Meeting
:::
::: {.cv-location}
Berlin, Germany
:::
::: {.cv-description}
**Oral presentation:** Transcriptome analysis reveals differential innate immune response of bovine macrophages to strains of the *Mycobacterium tuberculosis* complex
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
UCD Conway Festival of Research & Innovation
:::
::: {.cv-location}
Dublin, Ireland
:::
::: {.cv-description}
**Poster:** Transcriptome analysis reveals differential innate immune response to members of the *Mycobacterium tuberculosis* complex
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2014
:::
::: {.cv-title}
Wellcome Trust Final Year PhD Students' Meeting
:::
::: {.cv-location}
London, UK
:::
::: {.cv-description}
**Poster:** Transcriptome analysis reveals differential innate immune response to members of the *Mycobacterium tuberculosis* complex
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2013
:::
::: {.cv-title}
Association of Veterinary Teachers and Research Workers (AVTRW)
:::
::: {.cv-location}
Hillsborough, Ireland
:::
::: {.cv-description}
**Oral presentation:** Systems Biology of Host-Pathogen Interactions and Bovine Tuberculosis - Differential transcriptional response of bovine monocyte-derived macrophages following different mycobacterial infections
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2013
:::
::: {.cv-title}
Animal Health Ireland Workshop & Conference
:::
::: {.cv-location}
Rochestown Park Hotel, Cork
:::
::: {.cv-description}
**Poster:** Microarray analysis of the bovine macrophage response to *Mycobacterium bovis*, *M. bovis* Bacille Calmette-Guérin (BCG) and *M. avium* subspecies *paratuberculosis*
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2013
:::
::: {.cv-title}
Virtual Institute of Bioinformatics and Evolution (VIBE)
:::
::: {.cv-location}
Galway, Ireland
:::
::: {.cv-description}
**Oral presentation:** Systems Biology of Host-Pathogen Interactions and Bovine Tuberculosis - Differential transcriptional response of bovine monocyte-derived macrophages following different mycobacterial infections
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2013
:::
::: {.cv-title}
Computational Biology & Innovation Symposium
:::
::: {.cv-location}
Dublin, Ireland
:::
::: {.cv-description}
**Poster:** Microarray analysis of the bovine macrophage response to *Mycobacterium bovis*, *M. bovis* Bacille Calmette-Guérin (BCG) and *M. avium* subspecies *paratuberculosis*
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2013
:::
::: {.cv-title}
Dublin Academy of Pathogenomics & Infection Biology (DAPI)
:::
::: {.cv-location}
Dublin, Ireland
:::
::: {.cv-description}
**Poster:** Microarray analysis of the bovine macrophage response to *Mycobacterium bovis*, *M. bovis* Bacille Calmette-Guérin (BCG) and *M. avium* subspecies *paratuberculosis*
:::
:::

:::

::: {.cv-section}
## {{< fa certificate >}} Certifications

::: {.cv-entry}
::: {.cv-dates}
Jul 2017 -\
Sep 2017
:::
::: {.cv-title}
Machine Learning
:::
::: {.cv-location}
Coursera (Online)
:::
::: {.cv-description}
Supervised and unsupervised learning, best practices, and key algorithms.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2015 -\
Nov 2015
:::
::: {.cv-title}
Python for Genomic Data Science
:::
::: {.cv-location}
Coursera (Johns Hopkins University)
:::
::: {.cv-description}
Introduction to Python programming for genomic data analysis using Jupyter notebooks.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2015 -\
Nov 2015
:::
::: {.cv-title}
Command Line Tools for Genomic Data Science
:::
::: {.cv-location}
Coursera (Johns Hopkins University)
:::
::: {.cv-description}
Managing and analyzing large-scale genomic datasets using Unix command-line tools and workflows.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2015 -\
Nov 2015
:::
::: {.cv-title}
Bioconductor for Genomic Data Science
:::
::: {.cv-location}
Coursera (Johns Hopkins University)
:::
::: {.cv-description}
Using the Bioconductor project in R to perform analysis of genomic data.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2015 -\
Nov 2015
:::
::: {.cv-title}
Statistics for Genomic Data Science
:::
::: {.cv-location}
Coursera (Johns Hopkins University)
:::
::: {.cv-description}
Statistical methods for genomic data analysis including experimental design and inference.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Aug 2013 -\
Dec 2013
:::
::: {.cv-title}
Network Analysis in Systems Biology
:::
::: {.cv-location}
Coursera (Online)
:::
::: {.cv-description}
Data integration and statistical methods for systems biology including clustering, enrichment analysis, and network construction.
:::
:::

:::

[obds-training]: https://www.imm.ox.ac.uk/research/units-and-centres/mrc-wimm-centre-for-computational-biology/training/oxford-biomedical-data-science-training-programme
