---
title: "Latest news"
---

On this page, I list [recent updates](#recent-updates) regarding my research activities, publications, software releases, and [upcoming events](#save-the-date).

## Recent Updates

::: {.news-card}
::: {.news-date}
31 October 2025
:::

::: {.news-content}
**Funding opportunity outcome**

::: {.news-title}
Research Software Maintenance Fund: full application funding panels completed
:::

::: {.news-authors}
[Software Sustainability Institute](https://www.software.ac.uk/)
:::

::: {.news-role}
{{< fa user-circle >}} **My role:** Unsuccessful applicant at the Expression of Interest stage & Observer on a funding panel assessing applications.
:::

::: {.news-links}
[{{< fa file-text >}} Read blog post](https://www.software.ac.uk/blog/research-software-maintenance-fund-full-application-funding-panels-completed)
:::
:::
:::

::: {.news-card}
::: {.news-date}
17 October 2025
:::

::: {.news-content}
**New preprint published on bioRxiv**

::: {.news-title}
Fibroblast specialisation across microanatomy in a single-cell atlas of healthy human Achilles tendon
:::

::: {.news-authors}
Carla J. Cohen, Jolet Y. Mimpen, Alina Kurjan, Claudia Paul, Shreeya Sharma, Lorenzo Ramos-Mucci, Chinemerem T. Ikwanusi, Ali Cenk Aksu, Tracy Boakye Serebour, Marina Nikolic, **Kevin Rue-Albrecht**, Christopher Gibbons, Duncan Whitwell, Tom Cosker, Steven Gwilym, Ather Siddiqi, Raja Bhaskara Rajasekaran, Harriet Branford-White, Adam P. Cribbs, Philippa A. Hulley, David Sims, Mathew J. Baldwin, Sarah J. B. Snelling
:::

::: {.news-role}
{{< fa user-circle >}} **My role:** Contributed to the analysis of single-nuclei and spatial RNA-seq data.
:::

::: {.news-links}
[{{< fa file-text >}} Read preprint](https://www.biorxiv.org/content/10.1101/2025.10.17.683019v1)
:::
:::
:::

::: {.news-card}
::: {.news-date}
8 September 2025
:::

::: {.news-content}
**New preprint published on Research Square**

::: {.news-title}
The transcriptional repressor AEBP2 is indispensable for the epigenetic control of mimetic thymic epithelial cell differentiation and central self-tolerance induction
:::

::: {.news-authors}
Wei Wu, **Kevin Rue-Albrecht**, Qian Cheng, Fatima Dhalla, Mary Deadman, Rongyu Zang, Stephen Sansom, Yiyan Zheng, Georg Hollander
:::

::: {.news-role}
{{< fa user-circle >}} **My role:** Contributed to the analysis of bulk and single-cell RNA-seq data.
:::

::: {.news-links}
[{{< fa file-text >}} Read preprint](https://www.researchsquare.com/article/rs-7382433/v1)
:::
:::
:::

## Save the Date

::: {.event-card}
::: {.event-date}
31 January & 1 February 2026
:::

::: {.event-content}
::: {.event-title}
[Free and Open Source Developers' European Meeting (FOSDEM) 2026](https://fosdem.org/2026/)
:::

::: {.event-details}
{{< fa map-marker-alt >}} [ULB Solbosch Campus, Brussels, Belgium](https://maps.app.goo.gl/3L8ec4eEjwmrWcg86)  
{{< fa user-circle >}} **My role:** Interested in networking with [Bioinformatics & Computational Biology
](https://fosdem.org/2026/schedule/track/bioinformatics/) developers.
:::
:::
:::

::: {.event-card}
::: {.event-date}
28-30 April 2026
:::

::: {.event-content}
::: {.event-title}
[Collaborations Workshop 2026 (CW26)](https://www.singlecellgenomics2026.com/)
:::

::: {.event-details}
{{< fa map-marker-alt >}} [ICC Belfast, UK](https://maps.app.goo.gl/j1r3oYTqBvLQUep78)  
{{< fa users >}} Organiser: [Software Sustainability Institute](https://www.software.ac.uk/)  
{{< fa user-circle >}} **My role:** Interested in attending
:::
:::
:::

::: {.event-card}
::: {.event-date}
3-5 June 2026
:::

::: {.event-content}
::: {.event-title}
[European Bioconductor Conference 2026](https://eurobioc2026.bioconductor.org/)
:::

::: {.event-details}
{{< fa map-marker-alt >}} [Turku, Finland](https://maps.app.goo.gl/VAhXdCYVnxyt5ZP18)  
{{< fa users >}} [Meet the volunteers](https://eurobioc2026.bioconductor.org/pages/organizers.html)  
{{< fa user-circle >}} **My role:** On the organising committee
:::
:::
:::

::: {.event-card}
::: {.event-date}
22-24 June 2026
:::

::: {.event-content}
::: {.event-title}
[Galaxy Community Conference (GCC2026)](https://galaxyproject.org/events/gcc2026/)
:::

::: {.event-details}
{{< fa map-marker-alt >}} [Université Clermont Auvergne (UCA), France](https://maps.app.goo.gl/3t3s3fvDJUWxN8fC6)  
{{< fa user-circle >}} **My role:** Interested in attending
:::
:::
:::

::: {.event-card}
::: {.event-date}
10-12 August 2026
:::

::: {.event-content}
::: {.event-title}
[North American Bioconductor Conference 2026](https://bioc2026.bioconductor.org/)
:::

::: {.event-details}
{{< fa map-marker-alt >}} [Fred Hutch Cancer Center, Seattle, WA](https://maps.app.goo.gl/fJ9qiQBucd5PEKaD6)  
{{< fa users >}} [Meet the volunteers](https://bioc2026.bioconductor.org/organizers/)  
{{< fa user-circle >}} **My role:** Interested in attending
:::
:::
:::

::: {.event-card}
::: {.event-date}
Expected October 2026
:::

::: {.event-content}
::: {.event-title}
ELIXIR-UK All Hands 2026
:::

::: {.event-details}
{{< fa clock >}} [Edition 2025](https://elixiruknode.org/event/elixir-uk-all-hands-2025/)  
{{< fa user-circle >}} **My role:** Interested in attending
:::
:::
:::

::: {.event-card}
::: {.event-date}
Expected November 2026
:::

::: {.event-content}
::: {.event-title}
BioHackathon Europe 2026
:::

::: {.event-details}
{{< fa map-marker-alt >}} [Barcelona, Spain](https://maps.app.goo.gl/vyGxh7xCbmGizSzKA)  
{{< fa clock >}} [Edition 2025](https://biohackathon-europe.org/)  
{{< fa user-circle >}} **My role:** Interested in attending
:::
:::
:::


<!--
## Upcoming Events

### 04 December 2025

I will be hosting Wolfgang Huber as part of the WIMM Seminar Series on 4th December 2025. 

More details will be made available soon on the [WIMM Seminars page](https://www.imm.ox.ac.uk/research/units-and-centres/mrc-molecular-haematology-unit/seminars).
-->
