---
title: "Publications"
---

This page lists my research publications, organised by employment.
Expect some overlap in years for publications arising from transitions between positions.

## Sims Group (2020–present)

::: {.pub-card}
::: {.pub-title}
Learning and teaching biological data science in the Bioconductor community. [2025]{.pub-year}
:::
::: {.pub-authors}
Drnevich J, Tan FJ, Almeida-Silva F, Castelo R, Culhane AC, Davis S, Doyle MA, Geistlinger L, Ghazi AR, Holmes S, Lahti L, Mahmoud A, Nishida K, Ramos M, **Rue-Albrecht K**, Shih DJH, Gatto L, Soneson C.
:::
::: {.pub-links}
[Paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1012925) · [DOI](https://doi.org/10.1371/journal.pcbi.1012925) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/40261894/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Eleven quick tips for writing a Bioconductor package [2025]{.pub-year}
:::
::: {.pub-authors}
Charlotte Soneson; B.F. Francis Ouellette; Lori Shepherd; Marcel Ramos; **Kevin Rue-Albrecht**; Johannes Rainer; Hervé Pagès; Vincent J. Carey
:::
::: {.pub-links}
[Paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1012856) · [DOI](https://doi.org/10.1371/journal.pcbi.1012856) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/40106482/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Panpipes: a pipeline for multiomic single-cell and spatial transcriptomic data analysis. [2024]{.pub-year}
:::
::: {.pub-authors}
Curion F, Rich-Griffin C, Agarwal D, Ouologuem S, **Rue-Albrecht K**, May L, Garcia GEL, Heumos L, Thomas T, Lason W, Sims D, Theis FJ, Dendrou CA.
:::
::: {.pub-links}
[Paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03322-7) · [DOI](https://doi.org/10.1186/s13059-024-03322-7) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/38978088/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Capture-C: a modular and flexible approach for high-resolution chromosome conformation capture. [2022]{.pub-year}
:::
::: {.pub-authors}
Downes DJ, Smith AL, Karpinska MA, Velychko T, **Rue-Albrecht K**, Sims D, Milne TA, Davies JOJ, Oudelaar AM, Hughes JR.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41596-021-00651-w) · [DOI](https://doi.org/10.1038/s41596-021-00651-w) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/35121852/)
:::
:::

::: {.pub-card}
::: {.pub-title}
TreeSummarizedExperiment: a S4 class for data with hierarchical structure. [2020]{.pub-year}
:::
::: {.pub-authors}
Huang R, Soneson C, Ernst FGM, Rue-Albrecht KC, Yu G, Hicks SC, Robinson MD.
:::
::: {.pub-links}
[Paper](https://f1000research.com/articles/9-1246/v2) · [DOI](https://doi.org/10.12688/f1000research.26669.2) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/33274053/)
:::
:::

## Sansom Group (2017–2020)

::: {.pub-card}
::: {.pub-title}
The transcriptional repressor AEBP2 is indispensable for the epigenetic control of mimetic thymic epithelial cell differentiation and central self-tolerance induction [2025]{.pub-year}
:::
::: {.pub-authors}
Wei Wu; **Kevin Rue-Albrecht**; Qian Cheng; Fatima Dhalla; Mary Deadman; Rongyu Zang; Stephen Sansom; Yiyan Zheng; Georg Hollander
:::
::: {.pub-links}
[Paper](https://www.researchsquare.com/article/rs-7382433/v1) · [DOI](https://doi.org/10.21203/rs.3.rs-7382433/v1)
:::
:::

::: {.pub-card}
::: {.pub-title}
IL-1-driven stromal-neutrophil interactions define a subset of patients with inflammatory bowel disease that does not respond to therapies [2021]{.pub-year}
:::
::: {.pub-authors}
Friedrich M, Pohin M, Jackson MA, Korsunsky I, Bullers SJ, **Rue-Albrecht K**, Christoforidou Z, Sathananthan D, Thomas T, Ravindran R, Tandon R, Peres RS, Sharpe H, Wei K, Watts GFM, Mann EH, Geremia A, Attar M; Oxford IBD Cohort Investigators; Roche Fibroblast Network Consortium; McCuaig S, Thomas L, Collantes E, Uhlig HH, Sansom SN, Easton A, Raychaudhuri S, Travis SP, Powrie FM.
:::
::: {.pub-links}
[Paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1012856) · [DOI](https://doi.org/10.1038/s41591-021-01520-5) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/40106482/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Orchestrating single-cell analysis with Bioconductor. [2019]{.pub-year}
:::
::: {.pub-authors}
Amezquita RA, Lun ATL, Becht E, Carey VJ, Carpp LN, Geistlinger L, Marini F, **Rue-Albrecht K**, Risso D, Soneson C, Waldron L, Pagès H, Smith ML, Huber W, Morgan M, Gottardo R, Hicks SC.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41592-019-0654-x) · [DOI](https://doi.org/10.1038/s41592-019-0654-x) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/31792435/)
:::
:::

::: {.pub-card}
::: {.pub-title}
The Short Chain Fatty Acid Butyrate Imprints an Antimicrobial Program in Macrophages. [2019]{.pub-year}
:::
::: {.pub-authors}
Schulthess J, Pandey S, Capitani M, **Rue-Albrecht KC**, Arnold I, Franchini F, Chomka A, Ilott NE, Johnston DGW, Pires E, McCullagh J, Sansom SN, Arancibia-Cárcamo CV, Uhlig HH, Powrie F.
:::
::: {.pub-links}
[Paper](https://www.sciencedirect.com/science/article/pii/S1074761318305661?via%3Dihub) · [DOI](https://doi.org/10.1016/j.immuni.2018.12.018) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/30683619/)
:::
:::

::: {.pub-card}
::: {.pub-title}
iSEE: Interactive SummarizedExperiment Explorer [2018]{.pub-year}
:::
::: {.pub-authors}
**Rue-Albrecht K**, Marini F, Soneson C, Lun ATL
:::
::: {.pub-links}
[Paper](https://f1000research.com/articles/7-741/v1) · [DOI](https://doi.org/10.12688/f1000research.14966.1) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/30002819/)
:::
:::

## Ratcliffe Group (2016–2017)

This publication arose from a collaboration started during a short-term research position in the group of Prof. David Mole and Prof. Sir Peter Ratcliffe at the University of Oxford.

::: {.pub-card}
::: {.pub-title}
Invasive Salmonella exploits divergent immune evasion strategies in infected and bystander dendritic cell subsets. [2018]{.pub-year}
:::
::: {.pub-authors}
Aulicino A, **Rue-Albrecht KC**, Preciado-Llanes L, Napolitani G, Ashley N, Cribbs A, Koth J, Lagerholm BC, Ambrose T, Gordon MA, Sims D, Simmons A.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41467-018-07329-0) · [DOI](https://doi.org/10.1038/s41467-018-07329-0) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/30451854/)
:::
:::

## Wilkins Group (2015–2016)

These publications arose from my first postdoctoral research position in the group of Prof. Martin Wilkins at Imperial College London.

::: {.pub-card}
::: {.pub-title}
Whole-genome sequencing of a sporadic primary immunodeficiency cohort. [2020]{.pub-year}
:::
::: {.pub-authors}
Thaventhiran JED, Lango Allen H, Burren OS, Rae W, Greene D, Staples E, Zhang Z, Farmery JHR, Simeoni I, Rivers E, Maimaris J, Penkett CJ, Stephens J, Deevi SVV, Sanchis-Juan A, Gleadall NS, Thomas MJ, Sargur RB, Gordins P, Baxendale HE, Brown M, Tuijnenburg P, Worth A, Hanson S, Linger RJ, Buckland MS, Rayner-Matthews PJ, Gilmour KC, Samarghitean C, Seneviratne SL, Sansom DM, Lynch AG, Megy K, Ellinghaus E, Ellinghaus D, Jorgensen SF, Karlsen TH, Stirrups KE, Cutler AJ, Kumararatne DS, Chandra A, Edgar JDM, Herwadkar A, Cooper N, Grigoriadou S, Huissoon AP, Goddard S, Jolles S, Schuetz C, Boschann F; **Primary Immunodeficiency Consortium for the NIHR Bioresource**; Lyons PA, Hurles ME, Savic S, Burns SO, Kuijpers TW, Turro E, Ouwehand WH, Thrasher AJ, Smith KGC.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41586-020-2265-1) · [DOI](https://doi.org/10.1038/s41586-020-2265-1) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/32499645/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Bi-allelic Loss-of-Function CACNA1B Mutations in Progressive Epilepsy-Dyskinesia. [2019]{.pub-year}
:::
::: {.pub-authors}
Gorman KM, Meyer E, Grozeva D, Spinelli E, McTague A, Sanchis-Juan A, Carss KJ, Bryant E, Reich A, Schneider AL, Pressler RM, Simpson MA, Debelle GD, Wassmer E, Morton J, Sieciechowicz D, Jan-Kamsteeg E, Paciorkowski AR, King MD, Cross JH, Poduri A, Mefford HC, Scheffer IE, Haack TB, McCullagh G; Deciphering Developmental Disorders Study; UK10K Consortium; **NIHR BioResource**; Millichap JJ, Carvill GL, Clayton-Smith J, Maher ER, Raymond FL, Kurian MA.
:::
::: {.pub-links}
[Paper](https://www.cell.com/ajhg/fulltext/S0002-9297(19)30101-6?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0002929719301016%3Fshowall%3Dtrue) · [DOI](https://doi.org/10.1016/j.ajhg.2019.03.005) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/30982612/)
:::
:::

::: {.pub-card}
::: {.pub-title}
De Novo Truncating Mutations in WASF1 Cause Intellectual Disability with Seizures. [2018]{.pub-year}
:::
::: {.pub-authors}
Ito Y, Carss KJ, Duarte ST, Hartley T, Keren B, Kurian MA, Marey I, Charles P, Mendonça C, Nava C, Pfundt R, Sanchis-Juan A, van Bokhoven H, van Essen A, van Ravenswaaij-Arts C; **NIHR BioResource**; Care4Rare Canada Consortium; Boycott KM, Kernohan KD, Dyack S, Raymond FL.
:::
::: {.pub-links}
[Paper](https://www.cell.com/ajhg/fulltext/S0002-9297(18)30194-0) · [DOI](https://doi.org/10.1016/j.ajhg.2018.06.001) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/29961568/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Comprehensive Cancer-Predisposition Gene Testing in an Adult Multiple Primary Tumor Series Shows a Broad Range of Deleterious Variants and Atypical Tumor Phenotypes. [2018]{.pub-year}
:::
::: {.pub-authors}
Whitworth J, Smith PS, Martin JE, West H, Luchetti A, Rodger F, Clark G, Carss K, Stephens J, Stirrups K, Penkett C, Mapeta R, Ashford S, Megy K, Shakeel H, Ahmed M, Adlard J, Barwell J, Brewer C, Casey RT, Armstrong R, Cole T, Evans DG, Fostira F, Greenhalgh L, Hanson H, Henderson A, Hoffman J, Izatt L, Kumar A, Kwong A, Lalloo F, Ong KR, Paterson J, Park SM, Chen-Shtoyerman R, Searle C, Side L, Skytte AB, Snape K, Woodward ER; **NIHR BioResource Rare Diseases Consortium**; Tischkowitz MD, Maher ER.
:::
::: {.pub-links}
[Paper](https://www.cell.com/ajhg/fulltext/S0002-9297(18)30160-5) · [DOI](https://doi.org/10.1016/j.ajhg.2018.04.013) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/29909963/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Telomerecat: A ploidy-agnostic method for estimating telomere length from whole genome sequencing data. [2018]{.pub-year}
:::
::: {.pub-authors}
Farmery JHR, Smith ML; **NIHR BioResource - Rare Diseases**; Lynch AG.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41598-017-14403-y) · [DOI](https://doi.org/10.1038/s41598-017-14403-y) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/29358629/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Comprehensive Rare Variant Analysis via Whole-Genome Sequencing to Determine the Molecular Pathology of Inherited Retinal Disease. [2017]{.pub-year}
:::
::: {.pub-authors}

Carss KJ, Arno G, Erwood M, Stephens J, Sanchis-Juan A, Hull S, Megy K, Grozeva D, Dewhurst E, Malka S, Plagnol V, Penkett C, Stirrups K, Rizzo R, Wright G, Josifova D, Bitner-Glindzicz M, Scott RH, Clement E, Allen L, Armstrong R, Brady AF, Carmichael J, Chitre M, Henderson RHH, Hurst J, MacLaren RE, Murphy E, Paterson J, Rosser E, Thompson DA, Wakeling E, Ouwehand WH, Michaelides M, Moore AT; NIHR-BioResource Rare Diseases Consortium; Webster AR, Raymond FL.
:::
::: {.pub-links}
[Paper](linkinghub.elsevier.com/retrieve/pii/S0002929716305274) · [DOI](https://doi.org/10.1016/j.ajhg.2016.12.003) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/28041643/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Biallelic Mutation of ARHGEF18, Involved in the Determination of Epithelial Apicobasal Polarity, Causes Adult-Onset Retinal Degeneration. [2017]{.pub-year}
:::
::: {.pub-authors}
Arno G, Carss KJ, Hull S, Zihni C, Robson AG, Fiorentino A; UK Inherited Retinal Disease Consortium; Hardcastle AJ, Holder GE, Cheetham ME, Plagnol V; **NIHR Bioresource - Rare Diseases Consortium**; Moore AT, Raymond FL, Matter K, Balda MS, Webster AR.
:::
::: {.pub-links}
[Paper](https://linkinghub.elsevier.com/retrieve/pii/S0002929716305407) · [DOI](https://doi.org/10.1016/j.ajhg.2016.12.014) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/28132693/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Phenotypic Characterization of EIF2AK4 Mutation Carriers in a Large Cohort of Patients Diagnosed Clinically With Pulmonary Arterial Hypertension. [2017]{.pub-year}
:::
::: {.pub-authors}
Hadinnapola C, Bleda M, Haimel M, Screaton N, Swift A, Dorfmüller P, Preston SD, Southwood M, Hernandez-Sanchez J, Martin J, Treacy C, Yates K, Bogaard H, Church C, Coghlan G, Condliffe R, Corris PA, Gibbs S, Girerd B, Holden S, Humbert M, Kiely DG, Lawrie A, Machado R, MacKenzie Ross R, Moledina S, Montani D, Newnham M, Peacock A, Pepke-Zaba J, Rayner-Matthews P, Shamardina O, Soubrier F, Southgate L, Suntharalingam J, Toshner M, Trembath R, Vonk Noordegraaf A, Wilkins MR, Wort SJ, Wharton J; **NIHR BioResource–Rare Diseases Consortium**; UK National Cohort Study of Idiopathic and Heritable PAH; Gräf S, Morrell NW.
:::
::: {.pub-links}
[Paper](https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.117.028351) · [DOI](https://doi.org/10.1161/CIRCULATIONAHA.117.028351) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/28972005/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Plasma Metabolomics Implicates Modified Transfer RNAs and Altered Bioenergetics in the Outcomes of Pulmonary Arterial Hypertension. [2016]{.pub-year}
:::
::: {.pub-authors}
Rhodes CJ, Ghataorhe P, Wharton J, **Rue-Albrecht KC**, Hadinnapola C, Watson G, Bleda M, Haimel M, Coghlan G, Corris PA, Howard LS, Kiely DG, Peacock AJ, Pepke-Zaba J, Toshner MR, Wort SJ, Gibbs JS, Lawrie A, Gräf S, Morrell NW, Wilkins MR.
:::
::: {.pub-links}
[Paper](https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.116.024602) · [DOI](https://doi.org/10.1161/CIRCULATIONAHA.116.024602) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/27881557/)
:::
:::

## PhD Research (2011–2015)

These publications arose from my doctoral research and collaborations, jointly supervised by Prof. David MacHugh and Prof. Stephen Gordon, at University College Dublin.

::: {.pub-card}
::: {.pub-title}
RNA-Seq Transcriptome Analysis of Peripheral Blood From Cattle Infected With *Mycobacterium bovis* Across an Experimental Time Course. [2021]{.pub-year}
:::
::: {.pub-authors}
McLoughlin KE, Correia CN, Browne JA, Magee DA, Nalpas NC, **Rue-Albrecht K**, Whelan AO, Villarreal-Ramos B, Vordermeier HM, Gormley E, Gordon SV, MacHugh DE.
:::
::: {.pub-links}
[Paper](https://www.frontiersin.org/journals/veterinary-science/articles/10.3389/fvets.2021.662002/full) · [DOI](https://doi.org/10.3389/fvets.2021.662002) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/34124223/)
:::
:::

::: {.pub-card}
::: {.pub-title}
The bovine alveolar macrophage DNA methylome is resilient to infection with *Mycobacterium bovis*. [2019]{.pub-year}
:::
::: {.pub-authors}
O'Doherty AM, **Rue-Albrecht KC**, Magee DA, Ahting S, Irwin RE, Hall TJ, Browne JA, Nalpas NC, Walsh CP, Gordon SV, Wojewodzic MW, MacHugh DE.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41598-018-37618-z) · [DOI](https://doi.org/10.1038/s41598-018-37618-z) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/30728374/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Experimental infection of cattle with *Mycobacterium tuberculosis* isolates shows the attenuation of the human tubercle bacillus for cattle. [2018]{.pub-year}
:::
::: {.pub-authors}
Villarreal-Ramos B, Berg S, Whelan A, Holbert S, Carreras F, Salguero FJ, Khatri BL, Malone K, **Rue-Albrecht K**, Shaughnessy R, Smyth A, Ameni G, Aseffa A, Sarradin P, Winter N, Vordermeier M, Gordon SV.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/s41598-017-18575-5) · [DOI](https://doi.org/10.1038/s41598-017-18575-5) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/29343690/)
:::
:::

::: {.pub-card}
::: {.pub-title}
RNA Sequencing (RNA-Seq) Reveals Extremely Low Levels of Reticulocyte-Derived Globin Gene Transcripts in Peripheral Blood From Horses (Equus caballus) and Cattle (Bos taurus). [2018]{.pub-year}
:::
::: {.pub-authors}
Correia CN, McLoughlin KE, Nalpas NC, Magee DA, Browne JA, **Rue-Albrecht K**, Gordon SV, MacHugh DE.
:::
::: {.pub-links}
[Paper](https://www.frontiersin.org/journals/genetics/articles/10.3389/fgene.2018.00278/full) · [DOI](https://doi.org/10.3389/fgene.2018.00278) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/30154823/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Comparative 'omics analyses differentiate *Mycobacterium tuberculosis* and *Mycobacterium bovis* and reveal distinct macrophage responses to infection with the human and bovine tubercle bacilli. [2018]{.pub-year}
:::
::: {.pub-authors}
Malone KM, **Rue-Albrecht K**, Magee DA, Conlon K, Schubert OT, Nalpas NC, Browne JA, Smyth A, Gormley E, Aebersold R, MacHugh DE, Gordon SV.
:::
::: {.pub-links}
[Paper](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000163) · [DOI](https://doi.org/10.1099/mgen.0.000163) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/29557774/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Integrated computational prediction and experimental validation identifies promiscuous T cell epitopes in the proteome of *Mycobacterium bovis*. [2016]{.pub-year}
:::
::: {.pub-authors}
Farrell D, Jones G, Pirson C, Malone K, Rue-Albrecht K, Chubb AJ, Vordermeier M, Gordon SV.
:::
::: {.pub-links}
[Paper](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000071) · [DOI](https://doi.org/10.1099/mgen.0.000071) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/28348866/)
:::
:::

::: {.pub-card}
::: {.pub-title}
High-throughput transcriptomics reveals common and strain-specific responses of human macrophages to infection with *Mycobacterium abscessus* Smooth and Rough variants [2015]{.pub-year}
:::
::: {.pub-authors}
Aulicino A, Dinan AM, Miranda-CasoLuengo AA, Browne JA, **Rue-Albrecht K**, MacHugh DE, Loftus BJ.
:::
::: {.pub-links}
[Paper](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-2246-1) · [DOI](https://doi.org/10.1186/s12864-015-2246-1) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/26654095/)
:::
:::

::: {.pub-card}
::: {.pub-title}
Genome sequencing of the extinct Eurasian wild aurochs, Bos primigenius, illuminates the phylogeography and evolution of cattle. [2015]{.pub-year}
:::
::: {.pub-authors}
Park SD, Magee DA, McGettigan PA, Teasdale MD, Edwards CJ, Lohan AJ, Murphy A, Braud M, Donoghue MT, Liu Y, Chamberlain AT, **Rue-Albrecht K**, Schroeder S, Spillane C, Tai S, Bradley DG, Sonstegard TS, Loftus BJ, MacHugh DE.
:::
::: {.pub-links}
[Paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0790-2) · [DOI](https://doi.org/10.1186/s13059-015-0790-2) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/26498365/)
:::
:::

::: {.pub-card}
::: {.pub-title}
RNA sequencing provides exquisite insight into the manipulation of the alveolar macrophage by tubercle bacilli. [2015]{.pub-year}
:::
::: {.pub-authors}
Nalpas NC, Magee DA, Conlon KM, Browne JA, Healy C, McLoughlin KE, **Rue-Albrecht K**, McGettigan PA, Killick KE, Gormley E, Gordon SV, MacHugh DE.
:::
::: {.pub-links}
[Paper](https://www.nature.com/articles/srep13629) · [DOI](https://doi.org/10.1038/srep13629) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/26346536/)
:::
:::

::: {.pub-card}
::: {.pub-title}
GOexpress: an R/Bioconductor package for the identification and visualisation of robust gene ontology signatures through supervised learning of gene expression data [2016]{.pub-year}
:::
::: {.pub-authors}
**Rue-Albrecht K**, McGettigan PA, Hernández B, Nalpas NC, Magee DA, Parnell AC, Gordon SV, MacHugh DE.
:::
::: {.pub-links}
[Paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0971-3) · [DOI](https://doi.org/10.1186/s12859-016-0971-3) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/26968614/)
:::
:::

## Shields Group (2010)

This publication arose from a summer internship in the group of Prof. Denis Shields, under the supervision of Dr. Nora Khaldi.

::: {.pub-card}
::: {.pub-title}
Correlation of disorder between *S. cerevisiae* interacting proteins [2012]{.pub-year}
:::
::: {.pub-authors}
**Rue-Albrecht K**, Shields DC, Khaldi N.
:::
::: {.pub-links}
[Paper](https://pubs.rsc.org/en/content/articlelanding/2012/mb/c1mb05214d) · [DOI](https://doi.org/10.1039/c1mb05214d) · [PubMed](https://pubmed.ncbi.nlm.nih.gov/22108582/)
:::
:::

