---
title: "Teaching"
---

This page details my teaching experience.
For a summary, please see the [Teaching Experience](cv.qmd#fa-chalkboard-user-teaching-experience) section of my CV.

## 2025

::: {.cv-section}
::: {.cv-entry}
::: {.cv-dates}
Oct 2025
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2025 -\
Oct 2025
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2025
:::
::: {.cv-title}
iSEE therefore I explore (better)
:::
::: {.cv-location}
[European Bioconductor Conference 2025](https://eurobioc2025.bioconductor.org/) (Barcelona, Spain)
:::
::: {.cv-description}
Contributed to the organisation and delivery of a 1h45min workshop.

{{< fa book-open >}} [Workshop materials](https://isee.github.io/iSEEWorkshopEuroBioc2025/)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2025
:::
::: {.cv-title}
Orchestrating Large-Scale Single-Cell Analysis with Bioconductor
:::
::: {.cv-location}
[European Bioconductor Conference 2025](https://eurobioc2025.bioconductor.org/) (Barcelona, Spain)
:::
::: {.cv-description}
Two days of hands-on training covering the Bioconductor ecosystem for single-cell RNA-seq analysis (21 participants).

{{< fa calendar >}} [Event page](https://eurobioc2025.bioconductor.org/pages/carpentryworkshops.html) &nbsp; {{< fa book-open >}} [Lesson materials](https://carpentries-incubator.github.io/bioc-scrnaseq/)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2025
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2025
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2025
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2025
:::
::: {.cv-title}
MSc in Precision Cancer Medicine
:::
::: {.cv-location}
[Department of Oncology](https://www.oncology.ox.ac.uk/) (University of Oxford)
:::
::: {.cv-description}
Two online tutorials (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2025
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using Python
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering single-cell RNAseq data analysis using Python (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2025
:::
::: {.cv-title}
Python programming and data science
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Six days of hands-on training covering Python programming and data science principles (7 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2025
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (9 participants).
:::
:::
:::

## 2024

::: {.cv-section}
::: {.cv-entry}
::: {.cv-dates}
Dec 2024
:::
::: {.cv-title}
Containers for Reproducible Research
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
One day of hands-on training covering containerization technologies (e.g., Apptainer) for reproducible research (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Nov 2024
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2024
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (14 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2024 -\
Oct 2024
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2024
:::
::: {.cv-title}
Spatial Transcriptomics Data Camp
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering spatial transcriptomics data analysis (25 participants).

{{< fa newspaper >}} [News article](https://www.imm.ox.ac.uk/news/oxford-omics-data-camp-2024)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2024
:::
::: {.cv-title}
Navigating and expanding the iSEE universe
:::
::: {.cv-location}
[European Bioconductor Conference, Oxford](https://eurobioc2024.bioconductor.org/) (Oxford, UK)
:::
::: {.cv-description}
Co-organised and delivered a 40min workshop.

{{< fa book-open >}} [Workshop materials](https://isee.github.io/iSEEDemoEuroBioC2024/articles/workshop_isee_extension.html)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jul 2024
:::
::: {.cv-title}
Spatial Transcriptomics data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Four days of hands-on training covering spatial transcriptomics data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2024
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2024
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (10 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2024-\
May 2024
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2024
:::
::: {.cv-title}
MSc in Precision Cancer Medicine
:::
::: {.cv-location}
[Department of Oncology](https://www.oncology.ox.ac.uk/) (University of Oxford)
:::
::: {.cv-description}
Two online tutorials (14 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Mar 2024
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (10 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2024-\
Mar 2024
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2024
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (11 participants).
:::
:::
:::

## 2023

::: {.cv-section}
::: {.cv-entry}
::: {.cv-dates}
Oct 2023
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2023-\
Oct 2023
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2023
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2023
:::
::: {.cv-title}
iSEEing is believing: the iSEE package for efficient, interactive, and reproducible exploration of data
:::
::: {.cv-location}
[European Bioconductor Conference 2023](https://eurobioc2023.bioconductor.org/) (Ghent, Belgium)
:::
::: {.cv-description}
Contributed to the organisation of a 40min workshop.

{{< fa book-open >}} [Workshop materials](https://isee.github.io/iSEEDemoEuroBioC2023/articles/iSEEdemo.html)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2023
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering single-cell analysis using Seurat and Bioconductor (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2023
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Ten days of hands-on training covering R programming, data science principles, and genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2023
:::
::: {.cv-title}
MSc in Precision Cancer Medicine
:::
::: {.cv-location}
[Department of Oncology](https://www.oncology.ox.ac.uk/) (University of Oxford)
:::
::: {.cv-description}
Two online tutorials (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2023
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2023
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering single-cell analysis using Seurat and Bioconductor (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2023-\
Feb 2023
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Ten days of hands-on training covering R programming, data science principles, and genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2023
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (10 participants).
:::
:::
:::

## 2022

::: {.cv-section}
::: {.cv-entry}
::: {.cv-dates}
Oct 2022
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Five days of hands-on training covering single-cell analysis using Seurat and Bioconductor (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2022
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Ten days of hands-on training covering R programming, data science principles, and genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2022
:::
::: {.cv-title}
Version control using Git and GitHub
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
One day lesson of hands-on training covering version control using Git and GitHub as part of the 'Python programming and data science' curriculum (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2022
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Four days of hands-on training covering Linux command line tools for genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2022
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Fifteen days of hands-on training covering Linux and R programming for genomic and single-cell data analysis (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2022
:::
::: {.cv-title}
MSc in Precision Cancer Medicine
:::
::: {.cv-location}
[Department of Oncology](https://www.oncology.ox.ac.uk/) (University of Oxford)
:::
::: {.cv-description}
Three online tutorials (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2022-\
Feb 2022
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Fifteen days of hands-on training covering Linux and R programming for genomic and single-cell data analysis (8 participants).
:::
:::
:::

## 2021

::: {.cv-section}
::: {.cv-entry}
::: {.cv-dates}
Sep 2021-\
Oct 2021
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Fifteen days of hands-on training covering Linux and R programming for genomic and single-cell data analysis (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2021-\
Jun 2021
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Thirteen days of hands-on training covering Linux, Python, and R programming for genomic and single-cell data analysis (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2021-\
Feb 2021
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Thirteen days of hands-on training covering Linux, Python, and R programming for genomic and single-cell data analysis (8 participants).
:::
:::
:::

## 2020

::: {.cv-section}
::: {.cv-entry}
::: {.cv-dates}
Sep 2020-\
Oct 2020
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Sixteen days of hands-on training covering Linux, Python, and R programming for genomic and single-cell data analysis (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jul 2020
:::
::: {.cv-title}
Interactive visualization of SummarizedExperiment objects with iSEE
:::
::: {.cv-location}
[Bioconductor Conference 2020](https://bioc2020.bioconductor.org/) (Online)
:::
::: {.cv-description}
Co-organised and delivered a 55min online workshop.

{{< fa book-open >}} [Workshop materials](https://isee.github.io/iSEEWorkshop2020/) &nbsp; {{< fa brands youtube >}} [YouTube recording](https://youtu.be/qmoJtL8b438)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2020
:::
::: {.cv-title}
iSEE: Interactive visualization of SummarizedExperiment objects
:::
::: {.cv-location}
[SIB Days](https://sibdays.sib.swiss/) (Online)
:::
::: {.cv-description}
Co-organised and delivered a 2h30 online workshop.

{{< fa book-open >}} [Workshop materials](https://isee.github.io/iSEEWorkshop2020/)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2020-\
Jun 2020
:::
::: {.cv-title}
Oxford Biomedical Data Science (OBDS) Training Programme
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training] (Oxford, UK)
:::
::: {.cv-description}
Thirty days of hands-on training covering Linux, Python, and R programming for genomic and single-cell data analysis (8 participants).
:::
:::
:::

[obds-training]: https://www.imm.ox.ac.uk/research/units-and-centres/mrc-wimm-centre-for-computational-biology/training/oxford-biomedical-data-science-training-programme
